#pragma once
/****************************************
 * This is an autogenerated file, any   *
 * changes you make will be overwritten *
 ***************************************/
#define CACHE_SETS	64
#define CACHE_LINE	64
#define CACHE_ASSOC	8
#define CACHE_SIZE	32768

